### ISSUE TITLE
Disable silktouch spawner when ...

### ISSUE THREAD

**Issue by Okii35** [jredfox/silkspawners#2]
Hello.
Can you make it possible to disable the silktouch spawner option when a player already retrieves a spawner from an entity. Like that he can only once have the skeleton spawner, the zombie spawner, etc
And he can not multiply the identical spawner in his chests.

Exemple: The player "silktouch " a spawner of skeleton and on the other spawner of skeleton when he try to "silktouch" it will be destroy.

**Comment by jredfox** [comment]
Are you asking disabling it per entity that's a planned 2.0 feature the utility 1.0 re-write works as is unless it's a valid issue for the 1.0 I wont' fix it or enhance it unless I like the idea and it's not planned in the 2.0 edition

**Comment by jredfox** [comment]
After re-reading it your example makes no sense but, I might consider this for the 2.0 xml edition. Are you asking stacksize of 1 or only one per inventory or only one period? I don't think I will ever say one period I not sure about anything like only one per entity.

Maybe you could make an addon request I don't think disabling it like this is something for the main core of silkspanwers? The 2.0 xml edition will contain custom forge events and interfaces if your a coder you could easily cancel the event and stop the drop and also add stuff to the parser in xml code for configurations per spawner object yourself but, after typing this long response I don't think it's a job for the core function. I am leaving this closed but, not locked for responses

**Comment by jredfox** [comment]
Also note: this is the old github for future issues use:
https://github.com/jredfox/silkspawners_rewrite
